language: node_js
node_js:
  - node

cache: yarn

deploy:
  skip_cleanup: true

  provider: surge
  project: ./dist/
  domain: gracecolumbia.com

  on:
    branch: master

env:
  global:
    - NODE_ENV=production
